### ISSUE TITLE
Spam emails :(

### ISSUE THREAD

**Issue by sunnymatt** [cs4good/CSSGWebsite#1]
We've been getting a lot of spam emails on our website. Because we are rate-limited by the free tools we use (both the form submission and the Zapier plugin that forwards form submissions to our Slack), this means that spammy messages often eat up our capacity and prevent us from seeing actually useful messages. Plus, the spam makes it harder to sort through messages to find the good ones.

Potential solution:
- CAPTCHA before message gets sent?

**Comment by matthewkol186** [comment]
Resolved! Moved to Netlify forms which has better spam detection.
